const quotes = [
  // On starting with why
  "People don’t buy what you do; they buy why you do it. And what you do simply proves what you believe.",
  "When we tell people to do their jobs, we get workers. When we trust people to get the job done, we get leaders.",
  "Leaders are the ones who have the courage to go first, to put themselves at personal risk to open a path for others to follow.",
  "Working hard for something we don’t care about is called stress; working hard for something we love is called passion.",
  "The goal is not to be perfect by the end, the goal is to be better today.",
  "There are only two ways to influence human behavior: you can manipulate it or you can inspire it.",
  "A star wants to see herself rise to the top. A leader wants to see those around her become stars.",
  "If you want to feel happy, do something for yourself. If you want to feel fulfilled, do something for someone else.",
  "If you want to achieve anything in this world, you have to get used to the idea that not everyone will like you.",
  "Too many people confuse being rich or famous with being a leader. Wealth and fame are byproducts not qualifications to lead.",
  "You can easily judge the character of a man by how he treats those who can do nothing for him.",
  "Leadership is not a rank or a position, it is a choice – a choice to look after the person to the left of us and the person to the right of us.",
  "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.",
  "Always plan for the fact that no plan ever goes according to plan.",
  "Dream big, start small. But most of all, start.",
  // On teamwork and change (leadership)
  "A team is not a group of people that work together. A team is a group of people that trust each other.",
  "A leader’s job is not to do the work for others, it’s to help others figure out how to do it themselves, to get things done, and to succeed beyond what they thought possible.",
  "Hire people inspired to achieve something big over people who demand something big before they feel inspired.",
  "There is a difference between working together and working in the same office.",
  "When we lead with a finite mindset in an infinite game, it leads to all kinds of problems, the most common of which include the decline of trust, cooperation and innovation.",
  "Great companies don’t hire skilled people and motivate them, they hire already motivated people and inspire them.",
  "A culture is strong when people work with each other, for each other. A culture is weak when people work against each other, for themselves.",
  "If you hire people just because they can do a job, they’ll work for your money. But if you hire people who believe what you believe, they’ll work for you with blood and sweat and tears.",
  "Leaders don’t look for recognition from others, leaders look for others to recognize.",
  "At well led companies, people talk about the strength of the values. At poorly led companies, people complain about the pay and benefits.",
  "Achievement happens when we pursue and attain what we want. Success comes when we are in clear pursuit of why we want it.",
  "Under poor leaders we feel like we work for the company. With good leaders we feel like we work for each other.",
  "The leaders who get the most out of their people are the leaders who care most about their people.",
  "Stress and anxiety at work have less to do with the work we do and more to do with weak management and leadership.",
  "Leadership requires two things: a vision of the world that does not yet exist and the ability to communicate it.",
  "We achieve more when we chase the dream instead of the competition.",
  "Vision is the ability to talk about the future with such clarity it is as if we are talking about the past.",
  "A boss wants to pay for results, an employee wants recognition for effort. If a boss recognizes effort, they will get even better results.",
  "Returning from work feeling inspired, safe, fulfilled and grateful is a natural human right to which we are all entitled and not a modern luxury that only a few lucky ones are able to find.",
  "Customers will never love a company until the employees love it first.",
  "Be the leader you wish you had.",
  // On love and purpose (communication)
  "There is a difference between listening and waiting for your turn to speak.",
  "Passion alone can’t cut it. For passion to survive it needs structure. A WHY without HOW has little probability of success.",
  "Life is beautiful not because of the things we see or do. Life is beautiful because of the people we meet.",
  "When people are financially invested, they want a return. When people are emotionally invested, they want to contribute.",
  "Most of us live our lives by accident — we live as it happens. Fulfillment comes when we live our lives on purpose.",
  "Self confidence is the ability to exercise restraint in the face of disrespect and still show respect in response.",
  "If no one ever broke the rules, then we’d never advance.",
  "When we break eye contact to check our phones we degrade trust. Let’s keep our phones away from meals and meetings.",
  "As the Zen Buddhist saying goes, how you do anything is how you do everything.",
  "Admitting that I didn’t know something and asking for help was perhaps the single best lesson I ever learnt.",
  "Don’t show up to prove. Show up to improve.",
  "Confidence is believing in yourself. Arrogance is telling others you’re better than they are. Confidence inspires. Arrogance destroys.",
  "When you compete against everyone else, no one wants to help you. But when you compete against yourself, everyone wants to help you.",
  "The value of networking is not measured by the number of people we meet but by the number of people we introduce to others.",
  "One of the greatest things you can do is give your time and energy – things you will never get back.",
  "It is better to disappoint people with the truth than to appease them with a lie.",
  "Knowledge is understanding based on what has been studied and learned. Wisdom is understanding based on what has been felt and experienced.",
  "The primary ingredient for progress is optimism. The unwavering belief that something can be better drives the human race forward.",
  "I find, when you’re an optimist, life has a funny way of looking after you.",
  "Value is not determined by those who set the price. Value is determined by those who choose to pay it.",
  "The only way to ‘find out if it will work out’ is to do it.",
  "What good is an idea if it remains an idea? Try. Experiment. Iterate. Fail. Try again. Change the world.",
];

export const getRandomQuote = () => quotes[Math.floor(Math.random() * quotes.length)];
